# bmi_predictor/recommendations.py

recommendations = {
    'Underweight': {
        'diet': [
            'Increase your calorie intake with nutrient-dense foods.',
            'Eat more frequently and include snacks.',
            'Incorporate healthy fats like avocados and nuts.',
            'Increase your calorie intake with nutrient-dense foods',
            'Eat more frequently and include snacks',
            'Incorporate healthy fats like avocados and nuts',
            'Add smoothies and shakes to your diet',
            'Choose whole-grain breads and cereals',
            'Include lean protein sources like chicken and fish',
            'Use milk or cream in your coffee and soups',
            'Add cheese to your dishes',
            'Snack on nuts, seeds, and dried fruits',
            'Avoid drinking water before meals to save space for more calories',
            'Eat high-calorie, nutrient-rich foods like avocados and nut butters',
            'Include legumes like lentils and beans in your diet',
            'Use oils like olive and coconut in cooking',
            'Add powdered milk to soups and casseroles',
            'Eat sweet potatoes and starchy vegetables',
            'Consume full-fat dairy products',
            'Try to eat five to six smaller meals during the day',
            'Avoid low-calorie foods and drinks',
            'Include eggs in your breakfast',
            'Add granola or trail mix to yogurt',
            'Use peanut butter as a spread on bread',
            'Drink smoothies made with milk and fruit',
            'Eat high-calorie fruits like bananas and mangos',
            'Add honey or jam to your toast',
            'Use protein powder in your shakes',
            'Eat dark chocolate as a treat',
            'Incorporate fatty fish like salmon and mackerel',
            'Add cream cheese to your bagels',
            'Include chia seeds in your meals',
            'Eat more pasta and rice dishes',
            'Use butter generously in cooking',
            'Add extra cheese to your pizza',
            'Include olives in your salads',
            'Eat more hummus with vegetables',
            'Try adding coconut milk to your smoothies',
            'Make soups with heavy cream',
            'Include quinoa in your salads',
            'Eat more lamb and pork',
            'Add extra olive oil to your salads',
            'Include custard and puddings for dessert',
            'Drink whole milk',
            'Include high-calorie energy bars',
            'Use mayonnaise in your sandwiches',
            'Eat more casserole dishes',
            'Try snacking on cheese sticks',
            'Add flaxseeds to your yogurt',
            'Eat more baked beans',
            'Try incorporating polenta into your diet',
            'Add whipped cream to desserts',
            'Use thick sauces and gravies',
        ],
        'exercise': [
            'Focus on strength training to build muscle mass.',
            'Avoid excessive cardio exercises.',
            'Consider yoga or Pilates for flexibility and muscle tone.',
        ]
    },
    'Normal weight': {
        'diet': [
            'Maintain a balanced diet with a variety of nutrients.',
            'Include plenty of fruits and vegetables.',
            'Stay hydrated and avoid sugary drinks.',
            'Maintain a balanced diet with a variety of nutrients',
            'Include plenty of fruits and vegetables',
            'Stay hydrated and avoid sugary drinks',
            'Choose whole grains over refined grains',
            'Include lean protein sources in your diet',
            'Eat fish twice a week',
            'Limit your intake of red and processed meats',
            'Choose low-fat or fat-free dairy products',
            'Use healthy cooking methods like grilling and steaming',
            'Limit your intake of saturated and trans fats',
            'Eat a variety of protein sources, including plant-based proteins',
            'Avoid excessive salt and added sugars',
            'Include nuts and seeds in your diet',
            'Use herbs and spices for flavor instead of salt',
            'Drink water throughout the day',
            'Limit your intake of high-calorie snacks',
            'Include legumes like beans and lentils',
            'Eat more leafy green vegetables',
            'Choose healthy fats like olive oil and avocado',
            'Avoid sugary cereals and snacks',
            'Eat a healthy breakfast every day',
            'Include fiber-rich foods in your meals',
            'Limit your intake of sugary beverages',
            'Include probiotic foods like yogurt',
            'Eat a variety of colorful vegetables',
            'Choose low-sodium options',
            'Avoid processed and fast foods',
            'Include whole fruits instead of fruit juices',
            'Eat smaller, more frequent meals',
            'Limit alcohol consumption',
            'Avoid large portions',
            'Use portion control when eating out',
            'Include whole grain bread and pasta',
            'Eat more home-cooked meals',
            'Use healthy snacks like fruits and nuts',
            'Avoid fried foods',
            'Include healthy desserts like fruit salad',
            'Eat more plant-based meals',
            'Limit your intake of baked goods',
            'Avoid sugary condiments',
            'Include oats in your breakfast',
            'Choose lean cuts of meat',
            'Include tofu and tempeh',
            'Avoid heavy cream and butter',
            'Eat more soups and stews',
            'Choose low-fat cooking methods',
            'Limit your intake of cheese',
            'Eat more salads with a variety of vegetables',
            'Avoid sugary and high-fat dressings',
            'Include a variety of whole grains in your diet',


        ],
        'exercise': [
            'Engage in regular aerobic exercises like walking, running, or swimming.',
            'Include strength training exercises twice a week.',
            'Incorporate flexibility and balance exercises like yoga.',
        ]
    },
    'Overweight': {
        'diet': [
            'Reduce intake of high-calorie, low-nutrient foods.',
            'Increase consumption of fruits, vegetables, and lean proteins.',
            'Drink plenty of water and avoid sugary drinks.',
        ],
        'exercise': [
            'Engage in moderate-intensity aerobic activities like brisk walking.',
            'Include strength training exercises to build muscle.',
            'Increase daily activity by taking the stairs and walking more.',
        ]
    },
    'Obese': {
        'diet': [
            'Follow a calorie-restricted, balanced diet.',
            'Consult a nutritionist for a personalized meal plan.',
            'Avoid processed foods and sugary beverages.',
        ],
        'exercise': [
            'Start with low-impact aerobic activities like swimming or cycling.',
            'Gradually increase the duration and intensity of workouts.',
            'Include strength training exercises to build muscle.',
        ]
    },
    'Morbid Obesity': {
        'diet': [
            'Seek professional medical advice for a supervised diet plan.',
            'Focus on nutrient-dense, low-calorie foods.',
            'Monitor portion sizes and avoid high-calorie snacks.',
        ],
        'exercise': [
            'Begin with very low-impact exercises such as water aerobics or seated exercises.',
            'Gradually increase physical activity under medical supervision.',
            'Consider physical therapy to increase mobility safely.',
        ]
    }
}
