# Generated by Django 4.2.17 on 2025-01-06 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=15)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('not_paid', 'Not Paid')], default='not_paid', max_length=10)),
                ('service_type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], default='standard', max_length=10)),
                ('mode_of_service', models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup'), ('branch', 'Branch')], default='delivery', max_length=10)),
                ('collection_date', models.DateTimeField(blank=True, null=True)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('date_collected', models.DateTimeField(blank=True, null=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.cart')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=15)),
                ('order_date', models.DateTimeField()),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('not_paid', 'Not Paid')], max_length=10)),
                ('service_type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], max_length=10)),
                ('mode_of_service', models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup'), ('branch', 'Branch')], max_length=10)),
                ('date_collected', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.order')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
    ]
