# Generated by Django 4.2.17 on 2025-01-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedorder',
            name='collection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
