# Generated by Django 4.1.7 on 2023-03-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'permissions': [('view_attendance', 'Can view attendance'), ('view_grades', 'Can view grades')]},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('view_attendance', 'Can view attendance'), ('view_grades', 'Can view grades')]},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': [('view_attendance', 'Can view attendance'), ('edit_attendance', 'Can edit attendance'), ('delete_attendance', 'Can delete attendance'), ('view_grades', 'Can view grades'), ('edit_grades', 'Can edit grades'), ('delete_grades', 'Can delete grades')]},
        ),
        migrations.AlterField(
            model_name='admin',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='admin_users', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='admin_users', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
