# Generated by Django 4.1.7 on 2023-03-26 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_admin_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.address'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.gender'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
