# Generated by Django 4.1.7 on 2023-03-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_admin_address_alter_admin_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='address',
        ),
        migrations.AddField(
            model_name='admin',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='qualification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary'), ('O', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='admin',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
